//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project___13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public string Class_Number { get; set; }
        public Nullable<int> Seats { get; set; }
    }
}
