//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project___13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constraints
    {
        public int Id { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public string Day { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> LecturerID { get; set; }
        public Nullable<int> Lecture_type { get; set; }
        public Nullable<int> ClassID { get; set; }
    }
}
