//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project___13
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLecturer
    {
        public string userid { get; set; }
        public string proffession1 { get; set; }
        public string proffession2 { get; set; }
        public string proffession3 { get; set; }
        public string proffession4 { get; set; }
    }
}
