//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project___13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int loginid { get; set; }
        public string username_ { get; set; }
        public string password { get; set; }
    }
}
