//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project___13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string userid { get; set; }
        public string password { get; set; }
        public Nullable<int> permission { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string Email { get; set; }
        public string username { get; set; }
        public string Role { get; set; }
    }
}
